services:
  - type: web
    name: inventario-backend
    env: docker
    region: oregon
    plan: free
    dockerContext: ./BackendInventarioVentas
    dockerfilePath: ./BackendInventarioVentas/Dockerfile
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: jdbc:postgresql://db-inventario-ventas.cjsm86k8q6wu.sa-east-1.rds.amazonaws.com:5432/dbinventarioventas
      - key: SPRING_DATASOURCE_USERNAME
        value: postgres
      - key: SPRING_DATASOURCE_PASSWORD
        value: Jos300#2025
