services:
  - type: web
    name: inventario-backend
    env: docker
    region: oregon
    plan: free
    dockerContext: ./BackendInventarioVentas
    dockerfilePath: ./BackendInventarioVentas/Dockerfile
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: jdbc:postgresql://dpg-d0ppblbe5dus73e30hg0-a.oregon-postgres.render.com/databaseinventario
      - key: SPRING_DATASOURCE_USERNAME
        value: databaseinventario_user
      - key: SPRING_DATASOURCE_PASSWORD
        value: TAUdwa1RpNBU2xjgNxjkm7TAP1mPeQER
