services:
  - type: web
    name: inventario-backend
    env: docker
    region: oregon
    plan: free
    dockerContext: .
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: jdbc:postgresql://dpg-d0ppblbe5dus73e30hg0-a.oregon-postgres.render.com/databaseinventario
      - key: SPRING_DATASOURCE_USERNAME
        value: databaseinventario_user
      - key: SPRING_DATASOURCE_PASSWORD
        value: TAUdwa1RpNBU2xjgNxjkm7TAP1mPeQER
      - key: SPRING_JPA_HIBERNATE_DDL_AUTO
        value: update
      - key: SPRING_PROFILES_ACTIVE
        value: prod
